# Generated by Django 2.2.7 on 2019-12-04 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enlaces', '0003_auto_20191202_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='status',
            field=models.CharField(choices=[('o', 'opportunity'), ('d', 'declined'), ('r', 'requested'), ('p', 'pending'), ('c', 'confirmed'), ('d', 'deleted')], default='o', max_length=1),
        ),
    ]
