# Generated by Django 2.2.7 on 2019-12-07 18:24

from django.db import migrations, models
import enlaces.models


class Migration(migrations.Migration):

    dependencies = [
        ('enlaces', '0004_auto_20191204_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.URLField(validators=[enlaces.models.Link.validateURL]),
        ),
    ]
