# Generated by Django 2.2.7 on 2019-12-08 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enlaces', '0006_link_netloc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='status',
            field=models.CharField(choices=[('o', 'opportunity'), ('r', 'requested'), ('p', 'pending'), ('c', 'confirmed'), ('d', 'declined'), ('d', 'deleted')], default='o', max_length=1),
        ),
    ]
